//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Perpustakaan.Database_Perpustakaan
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class perpustakaanEntities3 : DbContext
    {
        public perpustakaanEntities3()
            : base("name=perpustakaanEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tb_buku> tb_buku { get; set; }
        public virtual DbSet<tb_buku_masuk> tb_buku_masuk { get; set; }
        public virtual DbSet<tb_detail_buku_masuk> tb_detail_buku_masuk { get; set; }
        public virtual DbSet<tb_detail_kembali> tb_detail_kembali { get; set; }
        public virtual DbSet<tb_detail_pinjam> tb_detail_pinjam { get; set; }
        public virtual DbSet<tb_kategori> tb_kategori { get; set; }
        public virtual DbSet<tb_kelas> tb_kelas { get; set; }
        public virtual DbSet<tb_kembali> tb_kembali { get; set; }
        public virtual DbSet<tb_keranjang> tb_keranjang { get; set; }
        public virtual DbSet<tb_pegawai> tb_pegawai { get; set; }
        public virtual DbSet<tb_penerbit> tb_penerbit { get; set; }
        public virtual DbSet<tb_pengirim> tb_pengirim { get; set; }
        public virtual DbSet<tb_penuliss> tb_penuliss { get; set; }
        public virtual DbSet<tb_pinjam> tb_pinjam { get; set; }
        public virtual DbSet<tb_rak> tb_rak { get; set; }
        public virtual DbSet<tb_riwayat_kembali> tb_riwayat_kembali { get; set; }
        public virtual DbSet<tb_riwayat_pinjam> tb_riwayat_pinjam { get; set; }
        public virtual DbSet<tb_role> tb_role { get; set; }
        public virtual DbSet<tb_satuan> tb_satuan { get; set; }
        public virtual DbSet<tb_siswa> tb_siswa { get; set; }
        public virtual DbSet<tb_status> tb_status { get; set; }
        public virtual DbSet<tb_user> tb_user { get; set; }
    }
}
