//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Perpustakaan.Database_Perpustakaan
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_buku
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_buku()
        {
            this.tb_detail_buku_masuk = new HashSet<tb_detail_buku_masuk>();
            this.tb_detail_kembali = new HashSet<tb_detail_kembali>();
            this.tb_detail_pinjam = new HashSet<tb_detail_pinjam>();
            this.tb_keranjang = new HashSet<tb_keranjang>();
            this.tb_rak = new HashSet<tb_rak>();
            this.tb_riwayat_kembali = new HashSet<tb_riwayat_kembali>();
            this.tb_riwayat_pinjam = new HashSet<tb_riwayat_pinjam>();
        }
    
        public int isbn { get; set; }
        public string judul_buku { get; set; }
        public int id_penulis { get; set; }
        public int id_penerbit { get; set; }
        public int id_kategori { get; set; }
        public System.DateTime tanggal_terbit { get; set; }
        public int jumlah_halaman { get; set; }
        public int stok { get; set; }
    
        public virtual tb_kategori tb_kategori { get; set; }
        public virtual tb_penerbit tb_penerbit { get; set; }
        public virtual tb_penuliss tb_penuliss { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_detail_buku_masuk> tb_detail_buku_masuk { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_detail_kembali> tb_detail_kembali { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_detail_pinjam> tb_detail_pinjam { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_keranjang> tb_keranjang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_rak> tb_rak { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_riwayat_kembali> tb_riwayat_kembali { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_riwayat_pinjam> tb_riwayat_pinjam { get; set; }
    }
}
