//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Perpustakaan.Database_Perpustakaan
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_pinjam
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_pinjam()
        {
            this.tb_detail_pinjam = new HashSet<tb_detail_pinjam>();
            this.tb_keranjang = new HashSet<tb_keranjang>();
        }
    
        public int id_pinjam { get; set; }
        public System.DateTime tanggal_pinjam { get; set; }
        public string nisn { get; set; }
        public int banyak_buku { get; set; }
        public int id_status { get; set; }
        public int id_username { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_detail_pinjam> tb_detail_pinjam { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_keranjang> tb_keranjang { get; set; }
        public virtual tb_siswa tb_siswa { get; set; }
        public virtual tb_user tb_user { get; set; }
        public virtual tb_status tb_status { get; set; }
    }
}
