//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Perpustakaan.Database_Perpustakaan
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_rak
    {
        public int id_rak { get; set; }
        public int isbn { get; set; }
        public int id_kategori { get; set; }
        public string lokasi_rak { get; set; }
    
        public virtual tb_buku tb_buku { get; set; }
        public virtual tb_kategori tb_kategori { get; set; }
    }
}
