//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Perpustakaan.Database_Perpustakaan
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_riwayat_kembali
    {
        public int id_riwayat_kembali { get; set; }
        public string nisn { get; set; }
        public int isbn { get; set; }
        public int qty { get; set; }
        public System.DateTime tanggal_kembali { get; set; }
        public int id_status { get; set; }
    
        public virtual tb_buku tb_buku { get; set; }
        public virtual tb_siswa tb_siswa { get; set; }
        public virtual tb_status tb_status { get; set; }
    }
}
