//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Perpustakaan.Database_Perpustakaan
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_user()
        {
            this.tb_buku_masuk = new HashSet<tb_buku_masuk>();
            this.tb_kembali = new HashSet<tb_kembali>();
            this.tb_pinjam = new HashSet<tb_pinjam>();
        }
    
        public int id_username { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public int id_pegawai { get; set; }
        public string nisn { get; set; }
        public int id_role { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_buku_masuk> tb_buku_masuk { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_kembali> tb_kembali { get; set; }
        public virtual tb_pegawai tb_pegawai { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_pinjam> tb_pinjam { get; set; }
        public virtual tb_role tb_role { get; set; }
        public virtual tb_siswa tb_siswa { get; set; }
    }
}
